# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-09 19:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gps', '0002_delete_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=100)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 9, 19, 14, 57, 563647, tzinfo=utc), verbose_name='Date')),
                ('description', models.TextField(help_text='Description')),
                ('gpx', models.FilePathField(path=b'/home/victor/Documents/Projet/poldrone')),
                ('pol', models.FilePathField(path=b'/home/victor/Documents/Projet/poldrone')),
            ],
        ),
    ]
