# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-09 19:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0003_processingnode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingnode',
            name='description',
            field=models.TextField(blank=True, help_text='Description'),
        ),
        migrations.AlterField(
            model_name='processingnode',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 9, 19, 31, 56, 317937, tzinfo=utc), verbose_name='Date'),
        ),
    ]
