# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-09 19:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0004_auto_20171209_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingnode',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 9, 19, 37, 2, 989711, tzinfo=utc), verbose_name='Date'),
        ),
    ]
