# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-09 21:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0005_auto_20171209_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingnode',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 9, 21, 32, 16, 995451, tzinfo=utc), verbose_name='Date'),
        ),
    ]
