# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-10 16:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0006_auto_20171209_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingnode',
            name='gpx',
            field=models.FileField(upload_to=b''),
        ),
        migrations.AlterField(
            model_name='processingnode',
            name='pol',
            field=models.FileField(upload_to=b''),
        ),
        migrations.AlterField(
            model_name='processingnode',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 10, 16, 49, 28, 299088, tzinfo=utc), verbose_name='Date'),
        ),
    ]
