# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-10 16:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0007_auto_20171210_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingnode',
            name='gpx',
            field=models.FileField(upload_to=b'/media/'),
        ),
        migrations.AlterField(
            model_name='processingnode',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 10, 16, 59, 49, 638198, tzinfo=utc), verbose_name='Date'),
        ),
    ]
