# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-10 17:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0008_auto_20171210_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingnode',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 10, 17, 3, 29, 781859, tzinfo=utc), verbose_name='Date'),
        ),
    ]
