# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-10 17:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0009_auto_20171210_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingnode',
            name='gpx',
            field=models.FileField(upload_to=b'/home/victor/Documents/Projet/poldrone/media'),
        ),
        migrations.AlterField(
            model_name='processingnode',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 10, 17, 4, 17, 699930, tzinfo=utc), verbose_name='Date'),
        ),
    ]
