# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-10 17:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0010_auto_20171210_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processingnode',
            name='pol',
        ),
        migrations.AddField(
            model_name='processingnode',
            name='pollution',
            field=models.FileField(default=django.utils.timezone.now, upload_to=b'/home/victor/Documents/Projet/poldrone/media'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='processingnode',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 10, 17, 14, 7, 913902, tzinfo=utc), verbose_name='Date'),
        ),
    ]
