# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-10 17:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0011_auto_20171210_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingnode',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 10, 17, 18, 3, 976108, tzinfo=utc), verbose_name='Date'),
        ),
    ]
