# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-10 18:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0014_auto_20171210_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingnode',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 10, 18, 55, 24, 860532, tzinfo=utc), verbose_name='Date'),
        ),
    ]
