# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-15 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0018_auto_20171215_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processingnode',
            name='time',
        ),
    ]
