# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-15 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0019_remove_processingnode_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingnode',
            name='time',
            field=models.DateField(auto_now=True, verbose_name='Date'),
        ),
    ]
