# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-15 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0020_processingnode_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processingnode',
            name='description',
        ),
        migrations.RemoveField(
            model_name='processingnode',
            name='time',
        ),
    ]
