# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-15 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0021_auto_20171215_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processingnode',
            name='gpx',
        ),
        migrations.RemoveField(
            model_name='processingnode',
            name='pollution',
        ),
    ]
