# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-15 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0022_auto_20171215_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingnode',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='processingnode',
            name='time',
            field=models.DateField(auto_now=True, verbose_name='Date'),
        ),
    ]
