# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-15 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0023_auto_20171215_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingnode',
            name='gpx',
            field=models.FileField(default='/', upload_to=b'/home/victor/Documents/Projet/poldrone/media'),
        ),
    ]
