# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-15 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0024_processingnode_gpx'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingnode',
            name='pollution',
            field=models.FileField(default='/', upload_to=b'/home/victor/Documents/Projet/poldrone/media'),
        ),
    ]
