# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-16 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0025_processingnode_pollution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingnode',
            name='gpx',
            field=models.FileField(upload_to=b'/home/victor/Documents/Projet/poldrone/media'),
        ),
        migrations.AlterField(
            model_name='processingnode',
            name='pollution',
            field=models.FileField(upload_to=b'/home/victor/Documents/Projet/poldrone/media'),
        ),
    ]
