# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-23 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0033_auto_20171217_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingnode',
            name='gpx',
            field=models.FileField(default='/home/victor/Documents/Projet/poldrone/media/victor_vaucel_2017-12-22_15-59-38.gpx', upload_to=b'/home/victor/Documents/Projet/poldrone/media'),
        ),
    ]
