# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-03 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0035_auto_20171223_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingnode',
            name='gpx',
            field=models.FileField(default='/media/Vol.gpx', upload_to=b'/media/'),
        ),
        migrations.AlterField(
            model_name='processingnode',
            name='pollution',
            field=models.FileField(default='/media/Vol.gpx', upload_to=b'/media/'),
        ),
    ]
