# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-03 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0036_auto_20180103_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingnode',
            name='gpx',
            field=models.FileField(default='/home/victor/Documents/Projet/poldrone/media/Vol.gpx', upload_to=b'/home/victor/Documents/Projet/poldrone/media/'),
        ),
        migrations.AlterField(
            model_name='processingnode',
            name='pollution',
            field=models.FileField(default='/home/victor/Documents/Projet/poldrone/media/Vol.gpx', upload_to=b'/home/victor/Documents/Projet/poldrone/media/'),
        ),
    ]
